# This is a basic workflow to help you get started with Actions

name: Nightly testing on big data files

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # run at 12:00 every day
    - cron: "0 12 1/1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pi
          pip install git+https://github.com/bionumpy/npstructures.git/@dev
          pip install git+https://github.com/bionumpy/bionumpy.git/@dev
          pip install -r requirements.txt
          
      - name: Run checks/benchmarks
        run: |
          python run_checks.py
          git config --global user.name "github action"
          git add -f results/*
          git add Readme.md
          git commit -am 'Test results'
      
      - name: Push results
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
          branch: ${{ github.ref }}

